# Generated by Django 2.1.11 on 2021-01-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210131_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='DSC00690.JPG', upload_to=''),
        ),
    ]
