# Generated by Django 2.1.11 on 2021-02-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210131_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to=''),
        ),
    ]
