# Generated by Django 3.0.8 on 2021-03-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20210326_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
